name: "OpenSCENARIO checker action"
description: "Check all openSCENARIO files that are committed and pushed"
author: "a.hege@rac.de"

inputs:
  CONF_FILE:
    description: "Configuration file for checks"
    required: true
  BASE_DIR:
    description: "Base directory to check"
    required: true
  CHECKER_JAR_FILE:
    description: "JAR file with the checker rules"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"