name: OpenSCENARIO Checker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Checker Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./checkOscAction
      with:
        TARGET_FOLDER: "targetFolder"