name: OpenSCENARIO Checker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Checker Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: change permission of checker file
      run: chmod -x ./ci/net.asam.openscenario.checker.example-0.9.0.jar
    - uses: ./checkOscAction
      with:
        CONF_FILE: ci/conf.yml
        BASE_DIR: targetFolder
        CHECKER_JAR_FILE: ci/net.asam.openscenario.checker.example-0.9.0.jar
        